Kinda got simulation working
uwrobotics/MarsRover2018 pull request #1
Opened 2017-09-28 02:31 UTC by AdityaMatam

Manual modification of working directory required. Alternative would have required modifications to various files in a few Husky packages.

2017-09-28 22:19 UTC, Oluwatoni commented
Why was this reopened?

2017-09-28 22:41 UTC, AdityaMatam commented
My changes caused some problems that I didn't want merged while I was fixing them, so I closed it in the meantime. It's good now though.

2017-09-28 23:20 UTC, archielee commented
Ok, so I want to set up CI first before I merge this in. I'll read it over though

2017-09-28 23:23 UTC, archielee requested changes
Also, can you add a doc in the `docs/` directory

2017-09-28 23:23 UTC, archielee commented on Workspace/src/rover_autonomy/src/ball_tracking.py
> +#!/usr/bin/env python
Please don't merge this in yet, I don't think it works well right? Also, we're re-doing it

2017-09-28 23:30 UTC, archielee requested changes

2017-09-28 23:30 UTC, archielee commented on Workspace/src/rover_autonomy/src/fake_laser.py
> +#!/usr/bin/env python
Do we still need fake_laser to fool the system?

2017-09-28 23:30 UTC, archielee commented on Workspace/src/rover_autonomy/src/gps_navigation.cpp
> +void tennisball_callback(const std_msgs::Int32MultiArray data) {
Is this enabled atm? Or do we hardcode `ball_valid` somewhere

2017-09-28 23:30 UTC, archielee commented on Workspace/src/rover_autonomy/src/gps_navigation.cpp
> +            ROS_WARN("state = STATE_WAITING_FOR_WAYPOINTS");
Don't use `ROS_WARN` for state changes, that's what `ROS_INFO` is for

2017-09-28 23:30 UTC, archielee commented on Workspace/src/twist_mux/.gitignore
> +*.pyc
We really shouldn't have individual .gitignores...

`twist_mux` can come in for now but I think it's going to be rewritten

2017-09-28 23:30 UTC, archielee commented on docs/Simulation Instructions.txt
> +Go to /opt/ros/kinetic/share/husky
This should be a Markdown file

2017-09-30 04:28 UTC, archielee commented
We should find a better place for the `husky_sim.rviz` and `setup_model.bash` files

2018-01-28 15:58 UTC, closed without merging