Science controller
uwrobotics/MarsRover2018 pull request #22
Opened 2018-05-28 06:38 UTC by zameerbharwani

With all the latest functionalities

2018-05-30 08:43 UTC, lijerryli commented on Workspace/src/science_controller/src/science.py
> +        if self.temperature_switch == 1:
switch to constant velocity, just send -1 or 1 depending on button pressed, if nothing pressed then send 0

2018-05-30 08:46 UTC, lijerryli commented on Workspace/src/science_controller/src/science.py
> +        if joy.axes[4] != 0:
always send the can messages associated with joypads (elevator + drill)

2018-05-30 08:47 UTC, lijerryli commented on Workspace/src/science_controller/src/science.py
> +    def send_info_1(self):
rename to more readable names

2018-05-30 08:47 UTC, lijerryli commented on Workspace/src/science_controller/src/science.py
> +        frame.dlc = 8
dlc = 4

2018-06-01 05:51 UTC, archielee requested changes

2018-06-01 05:51 UTC, archielee commented on Workspace/src/science_controller/src/science_no_LSs.py
> +        self.sub_xbox = rospy.Subscriber("/joy", Joy, self.callback_xbox)
change to /science_joy

2018-06-01 05:51 UTC, archielee commented on Workspace/src/science_no_LSs.py
> +        self.sub_xbox = rospy.Subscriber("/joy", Joy, self.callback_xbox)
change to science_joy

2018-06-01 10:44 UTC, merged